apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deployer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-deployer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins-deployer
  namespace: default


# Este archivo tiene el proposito de crear un service account para jenkins, con el fin de que pueda interactuar con el cluster de kubernetes y realizar tareas como despliegues, gestión de recursos, etc.

# Se otorga a Jenkins permisos de administrador en el cluster a traves de un ClusterRoleBinding, lo que le permite realizar cualquier acción en cualquier recurso dentro del cluster. Esto es necesario para que Jenkins pueda gestionar los recursos de Kubernetes de manera efectiva.

