apiVersion: v1
# Los Secrets son para guardar privadas(como contraseñas, tokens JWT, keys de SSH, etc)
kind: Secret
metadata:
  name: postgres-secret
# Tipo Opaque: k8s simplemente guardara las llaves sin darle formato especial
type: Opaque
# stringData: Permite que escribas contraseñas en texto plano aqui. Kubernetes se encargará detras de escena de transformarlo en base64 al guardarlo en su memoria para que no sea tan visible.
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: academy